---
default_config:

homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  currency: USD
  time_zone: "America/Los_Angeles"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      trusted_users:
        0.0.0.0/0: 1141ee80e0a647c1a4687d0b7631a019
      allow_bypass_login: true
    - type: homeassistant

debugpy:
  # host: "0.0.0.0"
  # port: 5678
  # start: false
  # wait: false

logger:
  default: warning
  logs:
    custom_components.frigate: debug
    homeassistant.components.mqtt: error

downloader:
  download_dir: www

camera:
  - platform: demo

panel_iframe:
  frigate:
    title: "Frigate"
    url: "http://localhost:5000"
    icon: "mdi:cctv"
