---
default_config:

logger:
  default: error
  logs:
    custom_components.frigate: debug
    homeassistant.components.mqtt: error

downloader:
  download_dir: www

homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  currency: USD
  time_zone: "America/Los_Angeles"
