---
default_config:

homeassistant:
  name: Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  country: US
  currency: USD
  time_zone: "America/Los_Angeles"
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 0.0.0.0/0
      trusted_users:
        0.0.0.0/0: 1141ee80e0a647c1a4687d0b7631a019
      allow_bypass_login: true
    - type: homeassistant
  packages:
    specific: !include specific_configuration.yaml

logger:
  default: error
  logs:
    custom_components.frigate: debug
    homeassistant.components.mqtt: error
