---
detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
mqtt:
  host: mqtt
go2rtc:
  streams:
    big_buck_bunny:
      # yamllint disable-line rule:line-length
      - exec:/usr/lib/ffmpeg/7.0/bin/ffmpeg -re -stream_loop -1 -i https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov -c copy -rtsp_transport tcp -f rtsp {{output}}
cameras:
  big_buck_bunny:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/big_buck_bunny
          input_args: preset-rtsp-restream-low-latency
          roles:
            - detect
            - record
            - audio
      output_args:
        record: preset-record-generic-audio-copy
    objects:
      track:
        - cat
