steps:
  build:
    image: python:3.13-slim
    when:
      event: pull_request
      branch: master

    commands:
      - ls
      - python -m venv venv
      - /bin/bash -c "source venv/bin/activate"
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements-dev.txt
      - pytest tests/